### ISSUE TITLE
Thanks for publishing.

### ISSUE THREAD

**Issue by pokulo** [pablo33/Shotwell-event2folder#27]
Hey Pablo,

I worked on the very same problems, in python as well. But went more in a manual GUI-based decision tool, which shall allow to decide for each event, if containing pictures shall remain in their folders, because the folder name is proper and the events name should be overwritten, or your way. Now I will try your script first and see if I have to finish my poor GUI scripting.

Finally it would be nice, if shotwell did more of what you added. To me its mainly the consistent folder names.

So thank you! I will also check out your other Date-detection tool.
Heinrich

**Comment by pokulo** [comment]
Your public repo encouraged me to at least publish my little work at https://github.com/pokulo/Shotwell-EventVsFolderGUI :)

**Comment by pablo33** [comment]
You are welcome, thanks for getting in touch. As you may have seen the concept of the script is to manage events, dates, names and everything in Shotwell. The script will reorganize in background your files in a event-oriented structure.

Although there is a function in the code to retrieve event's names from a path, this function is not used at all. (see def findeventname(Abranch):   function )
So if you already have a folder structure and it is already imported in Shotwell, you'll probably will have to manually name each event at Shotwell before running the script because the script goes in one direction and do not retrieve event's names from the filesystem. I think it could be rather ambiguous to retrieve them in an efficient way. On the other hand I think is better to do it manually. ( Ok, I know it takes time revise your events one by one).

Be careful if your file-tree contains other kind of files (.txt, .xls, ... whichever files whose are not managed with Shotwell), those files will not be processed and will remain on its places. (Some people use to attach files on their events or images).
This could be another option to implement in the future, although i think it's a bit dirty solution for an image library concept.

Thanks for your notes and for publishing your work!
